# Generated by Django 4.0.5 on 2022-06-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('sell_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('total_netto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.client')),
            ],
        ),
    ]
